=== rdkcentral/ralfpack/src/schemas/package_config_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/rdkcentral/oci-package-spec/main/schema/v1/package.schema.json",
  "title": "Package Metadata Schema",
  "description": "Schema defines a JSON structure that accurately represents the package metadata for use with OCI Packaging Format.",
  "type": "object",
  "properties": {
    "id": {
      "description": "The id field is a unique identifier of the package. Typically, this is represented in a reverse domain notation.",
      "type": "string",
      "pattern": "^(?!.*\\.\\.)[a-zA-Z0-9](?:[a-zA-Z0-9._-]*[a-zA-Z0-9])?$"
    },
    "specVersion": {
      "description": "The version of the RALF specification this package adheres to. Semantic Versioning (MAJOR.MINOR.PATCH) with optional pre-release tag.",
      "type": "string",
      "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.-]+)?$"
    },
    "version": {
      "description": "The semantic version number of the package, this is strictly checked to ensure it contains numbers separated by periods",
      "type": "string",
      "minLength": 1,
      "pattern": "^(0|[1-9][0-9]{0,8})([.](0|[1-9][0-9]{0,8})){0,3}$"
    },
    "versionName": {
      "description": "Optional version of the package as a user readable string.",
      "type": "string",
      "minLength": 1
    },
    "name": {
      "description": "User readable string that represents the name of the package.",
      "type": "string",
      "minLength": 1
    },
    "packageType": {
      "description": "Package type information.",
      "type": "string"
    },
    "packageSpecifier": {
      "description": "Specifier type information.",
      "type": "string"
    },
    "entryPoint": {
      "description": "Path to the entry point within the package.",
      "type": "string",
      "minLength": 1
    },
    "entryArgs": {
      "description": "Optional arguments passed to the entryPoint executable or script when launching the package.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dependencies": {
      "description": "Dependencies are specified with a package name to version range. The version range is a string which has one or more space-separated descriptors. Dependencies can also be identified with a tarball, digest, tag or git URL.",
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "permissions": {
      "description": "Section representing requested permission.",
      "type": "array",
      "items": {
        "type": "string",
        "description": "Permission string in URN notation."
      },
      "uniqueItems": true
    },
    "configuration": {
      "description": "Package specific configuration.",
      "type": "object",
      "properties": {
        "urn:rdk:config:env": {
          "description": "Environment variables (NAME → value) to inject into the application container.",
          "type": "object",
          "patternProperties": {
            "^[A-Za-z_][A-Za-z0-9_]*$": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "urn:rdk:config:runtime": {
          "description": "Runtime capability descriptor advertising the application types this runtime supports. REQUIRED for runtime packages.",
          "type": "object",
          "properties": {
            "supportedApplicationTypes": {
              "description": "The application types this runtime can host.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "description": "Application type identifier this runtime supports.",
                    "type": "string"
                  },
                  "args": {
                    "description": "Arguments passed to the runtime for this application type.",
                    "type": "object",
                    "additionalProperties": true
                  }
                },
                "required": [
                  "type"
                ]
              }
            }
          },
          "required": [
            "supportedApplicationTypes"
          ]
        },
        "urn:rdk:config:overrides": {
          "description": "Configuration overrides for dependencies.",
          "type": "object",
          "properties": {
            "application": {
              "description": "An undefined JSON blob that allows to override config values used by the application.",
              "type": "object",
              "additionalProperties": true
            },
            "runtime": {
              "description": "An undefined JSON blob that allows to override config values used by the runtime.",
              "type": "object",
              "additionalProperties": true
            }
          },
          "additionalProperties": false
        },
        "urn:rdk:config:log-levels": {
          "description": "Logging levels.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "fatal",
              "error",
              "warning",
              "milestone",
              "info",
              "debug"
            ]
          }
        },
        "urn:rdk:config:dial": {
          "description": "DIAL service details.",
          "type": "object",
          "properties": {
            "appNames": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "corsDomains": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "originHeaderRequired": {
              "type": "boolean"
            }
          }
        },
        "urn:rdk:config:application-lifecycle": {
          "description": "Set of the supported lifecycle parameters for the app or service.",
          "type": "object",
          "properties": {
            "supportedNonActiveStates": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "description": "Array of supported non-active lifecycle states."
            },
            "maxSuspendedSystemMemory": {
              "type": "string",
              "pattern": "^\\d+[GMBgmb]?$"
            },
            "maxTimeToSuspendMemoryState": {
              "type": "integer"
            },
            "startupTimeout": {
              "type": "integer"
            },
            "watchdogInterval": {
              "type": "integer"
            }
          },
          "required": [
            "supportedNonActiveStates",
            "maxSuspendedSystemMemory",
            "maxTimeToSuspendMemoryState"
          ],
          "additionalProperties": false
        },
        "urn:rdk:config:platform": {
          "description": "Specifies the platform on which the package is intended to run.",
          "type": "object",
          "properties": {
            "architecture": {
              "description": "The CPU architecture of the platform. Examples: 'amd64', 'arm', 'ppc64le'.",
              "type": "string"
            },
            "variant": {
              "description": "The CPU architecture variant. This field is OPTIONAL. Examples: 'v7' for ARM, 'z' for s390x.",
              "type": "string"
            },
            "os": {
              "description": "The operating system of the platform. Examples: 'linux', 'windows', 'darwin'.",
              "type": "string"
            }
          },
          "required": [
            "architecture",
            "os"
          ]
        },
        "urn:rdk:config:input-handling": {
          "description": "Input handling configuration.",
          "type": "object",
          "properties": {
            "keyIntercept": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "keyCapture": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "keyMonitor": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "urn:rdk:config:window": {
          "description": "Window configuration for the app.",
          "type": "object",
          "properties": {
            "virtualDisplaySize": {
              "type": "integer"
            }
          }
        },
        "urn:rdk:config:network": {
          "description": "Network services configuration.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "port": {
                "type": "integer"
              },
              "protocol": {
                "type": "string"
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "name",
              "port",
              "protocol",
              "type"
            ]
          }
        },
        "urn:rdk:config:memory": {
          "description": "Memory quota. Value can be specified with a G, M, or B suffix (case-insensitive). If no suffix is provided, the value is assumed to be in bytes.",
          "type": "object",
          "properties": {
            "system": {
              "type": "string",
              "pattern": "^\\d+[GMBgmb]?$"
            },
            "gpu": {
              "type": "string",
              "pattern": "^\\d+[GMBgmb]?$"
            }
          },
          "required": [
            "system",
            "gpu"
          ]
        },
        "urn:rdk:config:storage": {
          "description": "Storage quota. Value can be specified with a G, M, or B suffix (case-insensitive). If no suffix is provided, the value is assumed to be in bytes.",
          "type": "object",
          "properties": {
            "maxLocalStorage": {
              "type": "string",
              "pattern": "^\\d+[GMBgmb]?$"
            },
            "sharedStorageAppId": {
              "type": "string",
              "pattern": "^(?!.*\\.\\.)[a-zA-Z0-9](?:[a-zA-Z0-9._-]*[a-zA-Z0-9])?$"
            }
          },
          "required": [
            "maxLocalStorage"
          ]
        }
      },
      "additionalProperties": true
    }
  },
  "required": [
    "id",
    "specVersion",
    "version",
    "packageType"
  ],
  "additionalProperties": false,
  "allOf": [
    {
      "if": {
        "properties": {
          "packageType": {
            "const": "runtime"
          }
        },
        "required": [
          "packageType"
        ]
      },
      "then": {
        "properties": {
          "configuration": {
            "type": "object",
            "required": [
              "urn:rdk:config:runtime"
            ]
          }
        },
        "required": [
          "configuration"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "packageType": {
            "const": "resource"
          }
        },
        "required": [
          "packageType"
        ]
      },
      "else": {
        "required": [
          "entryPoint"
        ]
      }
    }
  ]
}

=== rdkcentral/ralfpack/testdata/package_config_v1.1.0.json
{
  "id": "com.sky.myapp",
  "specVersion": "1.1.0",
  "version": "1.2.3",
  "versionName": "1.2.3-beta",
  "name": "My Application",
  "packageType": "application",
  "packageSpecifier": "html",
  "entryPoint": "web/index.html",
  "entryArgs": ["--enable-feature-x", "--set-mode=dark"],
  "dependencies": {
    "rdk.browser.wpe": ">=1.1.0"
  },
  "permissions": [
    "urn:rdk:permission:home-app",
    "urn:rdk:permission:internet",
    "urn:rdk:permission:firebolt",
    "urn:rdk:permission:thunder",
    "urn:rdk:permission:rialto",
    "urn:rdk:permission:game-controller",
    "urn:rdk:permission:timeshift-buffer",
    "urn:rdk:permission:external-storage:read",
    "urn:rdk:permission:external-storage:write",
    "urn:rdk:permission:display-overlay",
    "urn:rdk:permission:compositor",
    "urn:entos:permission:as-access:5",
    "urn:entos:permission:as-player",
    "urn:entos:permission:mediarite:api",
    "urn:entos:permission:airplay",
    "urn:entos:permission:chromecast",
    "urn:entos:permission:bearer-token-authentication",
    "urn:entos:permission:sky-live",
    "urn:entos:permission:entitlements-info"
  ],
  "configuration": {
    "urn:rdk:config:overrides": {
      "application": {
        "colorTheme": "vivid"
      },
      "runtime": {
        "userAgent": "BBC_requirement_requesting_Operator_Specific_UserAgent",
        "libInject": "oiptv.js",
        "mTls": "/etc/certs/client_operator.cert"
      }
    },
    "urn:rdk:config:log-levels": ["error", "warning", "info"],
    "urn:rdk:config:dial": {
      "appNames": ["MyMediaApp", "MediaRemote"],
      "corsDomains": ["http://example.com", "https://my-media.com"],
      "originHeaderRequired": true
    },
    "urn:rdk:config:application-lifecycle": {
      "supportedNonActiveStates": ["paused", "suspended", "hibernated"],
      "maxSuspendedSystemMemory": "16M",
      "maxTimeToSuspendMemoryState": 10,
      "startupTimeout": 60,
      "watchdogInterval": 30
    },
    "urn:rdk:config:platform": {
      "architecture": "arm",
      "variant": "v7",
      "os": "linux"
    },
    "urn:rdk:config:keys": {
      "keyCapture": ["play", "pause", "stop", "fastForward", "rewind"],
      "keyMonitor": ["volumeUp", "volumeDown", "mute"]
    },
    "urn:rdk:config:window": {
      "virtualDisplaySize": 1080
    },
    "urn:rdk:config:memory": {
      "system": "256M",
      "gpu": "128M"
    },
    "urn:rdk:config:storage": {
      "maxLocalStorage": "32M",
      "sharedStorageAppId": "com.sky.myapp2"
    },
    "urn:rdk:config:network": [
      {
        "name": "netflix-mdx",
        "port": 8009,
        "protocol": "tcp",
        "type": "public"
      },
      {
        "name": "com.example.myapp.service",
        "port": 1234,
        "protocol": "tcp",
        "type": "exported"
      },
      {
        "name": "com.example.someotherapp.service",
        "port": 4567,
        "protocol": "tcp",
        "type": "imported"
      }
    ]
  }
}
